ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_dev
pip_install_packages:
  - name: docker
    version: 6.1.3
  - name: docker-compose

redmine_db_mysql: db
redmine_db_password: password
redmine_secret_key_base: supersecretkey

mysql_root_password: password
mysql_database: redmine