ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_dev
ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
pip_install_packages:
  - name: docker
    version: 6.1.3
  - name: docker-compose