ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_dev
pip_install_packages:
  - name: docker
    version: 6.1.3
  - name: docker-compose

redmine_db_mysql: db

datadog_site: us5.datadoghq.com
datadog_api_key: "{{vault_datadog_api_key}}"
datadog_checks:
  process:
    init_config:
    instances:
      - name: localhost
        url: http://0.0.0.0:8080