ansible_user: admin
ansible_ssh_private_key_file: ~/.ssh/id_dev
ansible_ssh_common_args: '-o StrictHostKeyChecking=accept-new'
pip_install_packages:
  - name: docker
    version: 6.1.3
  - name: docker-compose

mysql_image_version: "{{vault.mysql_image_version}}"
mysql_database: "{{vault.mysql_database}}"
mysql_host: "{{vault.mysql_host}}"
mysql_user: "{{vault.mysql_user}}"
mysql_password: "{{vault.mysql_password}}"

redmine_image_version: "{{vault.redmine_image_version}}"
redmine_port: "{{vault.redmine_port}}"
redmine_db_mysql: db
redmine_db_password: "{{vault.redmine_db_password}}"
redmine_secret_key_base: "{{vault.redmine_secret_key_base}}"
