mysql_image_version: "{{vault.mysql_image_version}}"
mysql_database: "{{vault.mysql_database}}"
mysql_host: "{{vault.mysql_host}}"
mysql_user: "{{vault.mysql_user}}"
mysql_password: "{{vault.mysql_password}}"

redmine_image_version: "{{vault.redmine_image_version}}"
redmine_port: "{{vault.redmine_port}}"
redmine_db_mysql: db
redmine_db_password: "{{vault.redmine_db_password}}"
redmine_secret_key_base: "{{vault.redmine_secret_key_base}}"

datadog_api_key: "{{vault.datadog_api_key}}"
datadog_site: us5.datadoghq.com
datadog_disable_untracked_checks: true
datadog_checks:
  process:
    init_config:
    instances:
      - name: localhost
        url: http://0.0.0.0:8080